spring:
  application:
    name: user-service

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000

server:
  port: 8082

logging:
  level:
    com.alekseev.userservice: DEBUG